package view;

import controller.Observer;
import controller.Observerable;
import controller.getData;
import java.util.ArrayList;

/**
 *
 * @author Dell
 */
public class MainController extends javax.swing.JFrame implements Observer{
    
    private Observerable observerable;

    /**
     * Creates new form Helicopter
     */
    public MainController(Observerable observerable) {
        initComponents();
        this.observerable = observerable;
        optionComboBox.removeAllItems();
//        optionComboBox.addItem("Select system");
        optionComboBox.addItem("Select the vehicle");
        optionComboBox.addItem("Helicopter");
        optionComboBox.addItem("Tank");
        optionComboBox.addItem("Submarine");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collectInfoBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AreaClearCheckBox = new javax.swing.JCheckBox();
        mainTextField = new javax.swing.JTextField();
        msgSendBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        optionComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        lblFuel = new javax.swing.JLabel();
        lblAmmo = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTxtArea = new javax.swing.JTextArea();
        privateMsgCheckBox = new javax.swing.JCheckBox();
        lblPosition = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Controller");
        setResizable(false);

        jLabel1.setText("Vehicle :");

        collectInfoBtn.setText("Collect Information ");
        collectInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectInfoBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Soldier Count:");

        jLabel4.setText("Fuel Amount:");

        AreaClearCheckBox.setText("Area Clear");
        AreaClearCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaClearCheckBoxActionPerformed(evt);
            }
        });

        msgSendBtn.setText("Send");
        msgSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgSendBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MAIN CONTROLLER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        optionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Ammo Amount:");

        jLabel7.setText("Position:");

        lblCount.setText(" Receiving...");

        lblFuel.setText(" Receiving...");

        lblAmmo.setText(" Receiving...");

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        mainTxtArea.setColumns(20);
        mainTxtArea.setRows(5);
        jScrollPane2.setViewportView(mainTxtArea);

        privateMsgCheckBox.setText("send private");

        lblPosition.setText(" Receiving...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgSendBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(privateMsgCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAmmo))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(optionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(collectInfoBtn))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCount)
                                                .addComponent(lblFuel)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblPosition)))
                                    .addGap(115, 115, 115)))
                            .addGap(13, 13, 13)
                            .addComponent(AreaClearCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AreaClearCheckBox)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(optionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collectInfoBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCount)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFuel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblAmmo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPosition))
                .addGap(16, 16, 16)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgSendBtn)
                    .addComponent(privateMsgCheckBox))
                .addGap(12, 12, 12))
        );

        pack();
        setLocation(50, 50); // Top-left corner
    }// </editor-fold>//GEN-END:initComponents

    private void AreaClearCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaClearCheckBoxActionPerformed
        // area clear status passing:
        String status;
        if (AreaClearCheckBox.isSelected()) {
            status="Area is Cleared";
        }else{
            status="Area is Not Cleared";
        }
        
        observerable.notifyObservers(status);
    }//GEN-LAST:event_AreaClearCheckBoxActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // slider state changed code:
        observerable.setSliderValue(jSlider2.getValue());
    }//GEN-LAST:event_jSlider2StateChanged

    private void msgSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgSendBtnActionPerformed
        // Get the message text from the input field
        String message = "Main Unit: " + mainTextField.getText();
        
        // Check if private messaging mode is enabled (checkbox is checked)
        if (privateMsgCheckBox.isSelected()) {
            // PRIVATE MODE: Send to only ONE selected observer
            int selectedIndex = optionComboBox.getSelectedIndex(); // Get which observer is selected (0=Select, 1=Helicopter, 2=Tank, 3=Submarine)
            ArrayList<Observer> observerList = observerable.getObserver(); // Get the list of all observers {main(0),helicopter(1),tank(2),submarine(3)}
            observerList.get(selectedIndex).setMessage(message); // Send message to ONLY the selected observer ("observerList.get(selectedIndex)." is what specifies which to send to, its kinda like parallel matching)
        } else {
            // BROADCAST MODE: Send to ALL observers
            observerable.sendMessage(message); // This sends the message to every observer in the list
        }
        
        // Clear the text field after sending the message
        mainTextField.setText("");
    }//GEN-LAST:event_msgSendBtnActionPerformed

    private void collectInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectInfoBtnActionPerformed
        // Collect information button:
        int options = optionComboBox.getSelectedIndex();
        if (options==0) {
            lblCount.setText("Select vehicle");
            lblFuel.setText("Select a vehicle");
            lblAmmo.setText("Select a vehicle");
            lblPosition.setText("Select a vehicle");

        }else{
        ArrayList<Observer> observerList = observerable.getObserver();
        
        int[] array = ((getData)observerList.get(options)).currentData();
        System.out.println(array[0]+""+array[1]+""+array[2]+""+array[3]);
        
        lblCount.setText(" "+array[0]);
        lblFuel.setText(" "+array[1]);
        lblAmmo.setText(" "+array[2]);
        
        if (array[3]==0) {
            lblPosition.setText(" Not in Position(Disabled)");
        }else if (array[3]==1) {
            lblPosition.setText(" In Position(Enabled)");
        }
            
        }

        
    }//GEN-LAST:event_collectInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AreaClearCheckBox;
    private javax.swing.JButton collectInfoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JTextField mainTextField;
    private javax.swing.JTextArea mainTxtArea;
    private javax.swing.JButton msgSendBtn;
    private javax.swing.JComboBox<String> optionComboBox;
    private javax.swing.JCheckBox privateMsgCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateStatus(String status) {
    }

    @Override
    public void setButton(int value) {
    }

    @Override
    public void setMessage(String message) {
        mainTxtArea.append(message+"\n");
    }

    @Override
    public void privateMessage() {
    }
}
